name: build & log
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: pnpm nx run-many -t build build-wp build-es >> build.log
      - run: ls -lah dist/ng-rspack/rspack >> build.log
      - run: ls -lah dist/ng-rspack/webpack >> build.log
      - run: ls -lah dist/ng-rspack/esbuild >> build.log
      - run: cat build.log
      - name: Commit build.log
        run: |
          git config --local user.email "bozonedouard@gmail.com"
          git config --local user.name "Edouard Bozon"
          git add build.log
          git commit -m "docs: update build.log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
