name: build & log
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: sudo apt install hyperfine -y
      - run: pnpm install
      - run: pnpm nx run-many -t build build-wp build-es -p mfe1
      - run: echo "rspack" >> build.log && ls -lah dist/mfe1/rspack >> build.log
      - run: echo "webpack" >> build.log && ls -lah dist/mfe1/webpack >> build.log
      - run: echo "esbuild" >> build.log && ls -lah dist/mfe1/esbuild/browser >> build.log
      - run: cat build.log
      - run: hyperfine -n "Webpack" "pnpm nx build-wp mfe1" -n "Rspack" "pnpm nx build mfe1" -n "Esbuild" "pnpm nx build-es mfe1" --prepare "rm -rf .angular dist" --export-markdown perf.md
      - name: Commit & Push
        run: |
          git config --local user.email "bozonedouard@gmail.com"
          git config --local user.name "Edouard Bozon"
          git add build.log perf.md
          git commit -m "chore: update perf logs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
